//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompra
    {
        public int Cop_Id { get; set; }
        public string Cop_NumFactura { get; set; }
        public Nullable<System.DateTime> Cop_Fecha { get; set; }
        public Nullable<int> Prd_Id { get; set; }
        public Nullable<int> Cop_Cantidad { get; set; }
        public bool Cop_Estado { get; set; }
        public int Cop_UsuarioCrea { get; set; }
        public System.DateTime Cop_FechaCrea { get; set; }
        public Nullable<int> Cop_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Cop_FechaModifica { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        public virtual tblProducto tblProducto { get; set; }
    }
}
