//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCiudade
    {
        public tblCiudade()
        {
            this.tblDirecciones = new HashSet<tblDireccione>();
        }
    
        public int Ciu_Codigo { get; set; }
        public string Ciu_Descripcion { get; set; }
        public Nullable<int> Dep_Codigo { get; set; }
        public Nullable<bool> Ciu_Activo { get; set; }
        public Nullable<int> Ciu_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> Ciu_FechaCrea { get; set; }
        public Nullable<int> Ciu_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Ciu_FechaModifica { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        public virtual tblDepartamento tblDepartamento { get; set; }
        public virtual ICollection<tblDireccione> tblDirecciones { get; set; }
    }
}
