//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCargo()
        {
            this.tblCargosPersonas = new HashSet<tblCargosPersona>();
        }
    
        public int Carg_Id { get; set; }
        public string Carg_Descripcion { get; set; }
        public int Carg_EsActivo { get; set; }
        public int Carg_UsuarioCrea { get; set; }
        public System.DateTime Carg_FechaCrea { get; set; }
        public Nullable<int> Carg_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Carg_FechaModifica { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCargosPersona> tblCargosPersonas { get; set; }
    }
}
