//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCiudade
    {
        public tblCiudade()
        {
            this.tblDirecciones = new HashSet<tblDireccione>();
        }
    
        public int Ciu_Codigo { get; set; }
        public string Ciu_Descripcion { get; set; }
        public Nullable<int> Dep_Codigo { get; set; }
        public Nullable<bool> Ciu_Activo { get; set; }
        public Nullable<int> Ciu_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> Ciu_FechaCrea { get; set; }
        public Nullable<int> Ciu_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Ciu_FechaModifica { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        public virtual tblDepartamento tblDepartamento { get; set; }
        public virtual ICollection<tblDireccione> tblDirecciones { get; set; }
    }
}
