//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCategoria()
        {
            this.tblProductos = new HashSet<tblProducto>();
        }
    
        public int Cat_Id { get; set; }
        public string Cat_Descripcion { get; set; }
        public bool Cat_Estado { get; set; }
        public int Cat_UsuarioCrea { get; set; }
        public System.DateTime Cat_FechaCrea { get; set; }
        public Nullable<int> Cat_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Cat_FechaModifica { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducto> tblProductos { get; set; }
    }
}
