//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersona
    {
        public tblPersona()
        {
            this.tblVentaEncabezadoes = new HashSet<tblVentaEncabezado>();
            this.tblCargosPersonas = new HashSet<tblCargosPersona>();
        }
    
        public int Per_Id { get; set; }
        public string Per_Identidad { get; set; }
        public string Per_Rtn { get; set; }
        public string Per_Nombres { get; set; }
        public string Per_PrimerApellido { get; set; }
        public string Per_SegundoApellido { get; set; }
        public string Per_Sexo { get; set; }
        public Nullable<int> Dir_Id { get; set; }
        public string Per_Telefono { get; set; }
        public string Per_Correo { get; set; }
        public int Per_EsActivo { get; set; }
        public int Per_UsuarioCrea { get; set; }
        public System.DateTime Per_FechaCrea { get; set; }
        public Nullable<int> Per_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Per_FechaModifica { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        public virtual ICollection<tblVentaEncabezado> tblVentaEncabezadoes { get; set; }
        public virtual ICollection<tblCargosPersona> tblCargosPersonas { get; set; }
        public virtual tblDireccione tblDireccione { get; set; }
    }
}
