//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProveedore()
        {
            this.tblProductos = new HashSet<tblProducto>();
        }
    
        public int Pro_Id { get; set; }
        public string Pro_Empresa { get; set; }
        public string Pro_RepNombreS { get; set; }
        public string Pro_RepPriApellido { get; set; }
        public string Pro_RepSegApellido { get; set; }
        public Nullable<int> Dir_Id { get; set; }
        public string Pro_TelFijo { get; set; }
        public string Pro_TelMovil { get; set; }
        public string Pro_Email { get; set; }
        public string Pro_PaginaWeb { get; set; }
        public bool Pro_Estado { get; set; }
        public int Pro_UsuarioCrea { get; set; }
        public System.DateTime Pro_FechaCrea { get; set; }
        public Nullable<int> Pro_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Pro_FechaModifica { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducto> tblProductos { get; set; }
        public virtual tblDireccione tblDireccione { get; set; }
    }
}
