//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblventadetalle
    {
        public int VentDet_Id { get; set; }
        public Nullable<int> VentEnc_Id { get; set; }
        public Nullable<int> Prd_Id { get; set; }
        public Nullable<decimal> VentDet_Precio { get; set; }
        public Nullable<int> VentDet_Cantidad { get; set; }
        public Nullable<decimal> VentDet_Descuento { get; set; }
        public string VentDet_Impuesto { get; set; }
        public Nullable<decimal> VentDet_Subtotal { get; set; }
        public Nullable<bool> VentDet_Activo { get; set; }
        public Nullable<int> VentDet_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> VentDet_FechaCrea { get; set; }
        public Nullable<int> VentDet_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> VentDet_FechaModifica { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblUsuario tblUsuario1 { get; set; }
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblVentaEncabezado tblVentaEncabezado { get; set; }
    }
}
