//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Usuario
    {
        public int IdU { get; set; }
        public string Nombre { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> Act { get; set; }
        public string Adm { get; set; }
    }
}
