//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Usuario
    {
        public int IdU { get; set; }
        public string Nombre { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> Act { get; set; }
        public string Adm { get; set; }
    }
}
